In [1]:
import nltk
import re
import heapq
import numpy as np

In [2]:
paragraph= "The Taj Mahal was built by Emperor Shah Jahan"

In [3]:
words=nltk.word_tokenize(paragraph)

In [4]:
tagged_words=nltk.pos_tag(words)

In [5]:
namedEntity= nltk.ne_chunk(tagged_words)

In [6]:
namedEntity.draw()

# BOW MODEL

In [35]:
paragraph= "Beans. I was trying to explain to somebody as we were flying in, that’s corn. That’s beans in flying mood."

In [36]:
sentences=nltk.sent_tokenize(paragraph)

In [37]:
for i in range(len(sentences)):
    sentences[i]= sentences[i].lower()
    sentences[i]=re.sub(r"\W",' ',sentences[i])
    sentences[i]=re.sub(r"\s+"," ",sentences[i])
    print(sentences[i])

beans 
i was trying to explain to somebody as we were flying in that s corn 
that s beans in flying mood 


In [38]:
word2count={}

# Creating the histogram

In [39]:
for data in sentences:
    words= nltk.word_tokenize(data)
    for word in words:
        if word not in word2count.keys():
            word2count[word]=1
        else:
            word2count[word]+=1
print(word2count)

{'beans': 2, 'i': 1, 'was': 1, 'trying': 1, 'to': 2, 'explain': 1, 'somebody': 1, 'as': 1, 'we': 1, 'were': 1, 'flying': 2, 'in': 2, 'that': 2, 's': 2, 'corn': 1, 'mood': 1}


In [41]:
freq_words=heapq.nlargest(10,word2count,key=word2count.get)  # take 10 most frequent words
print(freq_words)

['beans', 'to', 'flying', 'in', 'that', 's', 'i', 'was', 'trying', 'explain']


In [42]:
x=[]

In [43]:
for data in sentences:
    vector=[]
    for word in freq_words:
        if word in nltk.word_tokenize(data):
            vector.append(1)
        else:
            vector.append(0)
    x.append(vector)
print(x)
        

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 0, 1, 1, 1, 1, 0, 0, 0, 0]]


In [45]:
x= np.asarray(x)

In [46]:
print(x)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 1]
 [1 0 1 1 1 1 0 0 0 0]]
