In [13]:
import nltk
import re
import heapq
import numpy as np

In [19]:
paragraph="Beans. I was trying to explain to somebody as we were flying in, that’s corn. That’s beans in flying mood."

In [20]:
sentences=nltk.sent_tokenize(paragraph)

In [21]:
for i in range(len(sentences)):
    sentences[i]= sentences[i].lower()
    sentences[i]=re.sub(r"\W",' ',sentences[i])
    sentences[i]=re.sub(r"\s+"," ",sentences[i])
    print(sentences[i])

beans 
i was trying to explain to somebody as we were flying in that s corn 
that s beans in flying mood 


In [22]:
word2count={}
for data in sentences:
    words= nltk.word_tokenize(data)
    for word in words:
        if word not in word2count.keys():
            word2count[word]=1
        else:
            word2count[word]+=1
print(word2count)

{'beans': 2, 'i': 1, 'was': 1, 'trying': 1, 'to': 2, 'explain': 1, 'somebody': 1, 'as': 1, 'we': 1, 'were': 1, 'flying': 2, 'in': 2, 'that': 2, 's': 2, 'corn': 1, 'mood': 1}


In [24]:
freq_words=heapq.nlargest(10,word2count,key=word2count.get)  # take 10 most frequent words
print(freq_words)

['beans', 'to', 'flying', 'in', 'that', 's', 'i', 'was', 'trying', 'explain']


# IDF Matrix

In [25]:
word_idf={}
for word in freq_words:
    doc_count=0                      # No of docs containing that specific word
    for data in sentences:
        if word in nltk.word_tokenize(data):
            doc_count+=1
    word_idf[word]= np.log((len(sentences)/doc_count)+1)     # +1 is a bias, not necessary to use it
print(word_idf)
    

{'beans': 0.91629073187415511, 'to': 1.3862943611198906, 'flying': 0.91629073187415511, 'in': 0.91629073187415511, 'that': 0.91629073187415511, 's': 0.91629073187415511, 'i': 1.3862943611198906, 'was': 1.3862943611198906, 'trying': 1.3862943611198906, 'explain': 1.3862943611198906}


# TF Matrix

In [27]:
tf_matrix= {}

for word in freq_words:
    doc_tf=[]        
    for data in sentences:
        frequency = 0
        for w in nltk.word_tokenize(data):
            if w== word:
                frequency+=1
        tf_word = frequency/len(nltk.word_tokenize(data))
        doc_tf.append(tf_word)
    tf_matrix[word]=doc_tf


print(tf_matrix)

{'beans': [1.0, 0.0, 0.16666666666666666], 'to': [0.0, 0.13333333333333333, 0.0], 'flying': [0.0, 0.06666666666666667, 0.16666666666666666], 'in': [0.0, 0.06666666666666667, 0.16666666666666666], 'that': [0.0, 0.06666666666666667, 0.16666666666666666], 's': [0.0, 0.06666666666666667, 0.16666666666666666], 'i': [0.0, 0.06666666666666667, 0.0], 'was': [0.0, 0.06666666666666667, 0.0], 'trying': [0.0, 0.06666666666666667, 0.0], 'explain': [0.0, 0.06666666666666667, 0.0]}


# TF-IDF Calculation

In [28]:
tfidf_matrix = []
for word in tf_matrix.keys():
    tfidf= []
    for value in tf_matrix[word]:
        score = value * word_idf[word]
        tfidf.append(score)
    tfidf_matrix.append(tfidf)
    
print(tfidf_matrix)

[[0.91629073187415511, 0.0, 0.15271512197902584], [0.0, 0.18483924814931874, 0.0], [0.0, 0.061086048791610337, 0.15271512197902584], [0.0, 0.061086048791610337, 0.15271512197902584], [0.0, 0.061086048791610337, 0.15271512197902584], [0.0, 0.061086048791610337, 0.15271512197902584], [0.0, 0.092419624074659368, 0.0], [0.0, 0.092419624074659368, 0.0], [0.0, 0.092419624074659368, 0.0], [0.0, 0.092419624074659368, 0.0]]


In [30]:
x= np.asarray(tfidf_matrix)
print(x)

[[ 0.91629073  0.          0.15271512]
 [ 0.          0.18483925  0.        ]
 [ 0.          0.06108605  0.15271512]
 [ 0.          0.06108605  0.15271512]
 [ 0.          0.06108605  0.15271512]
 [ 0.          0.06108605  0.15271512]
 [ 0.          0.09241962  0.        ]
 [ 0.          0.09241962  0.        ]
 [ 0.          0.09241962  0.        ]
 [ 0.          0.09241962  0.        ]]


In [31]:
x=np.transpose(x)
print(x)

[[ 0.91629073  0.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.18483925  0.06108605  0.06108605  0.06108605  0.06108605
   0.09241962  0.09241962  0.09241962  0.09241962]
 [ 0.15271512  0.          0.15271512  0.15271512  0.15271512  0.15271512
   0.          0.          0.          0.        ]]
